### ISSUE TITLE
App banner in the header does not link to home page

### ISSUE THREAD

**Issue by grishick** [HEO-Platform/heo-web#91]
Clicking on app banner (i18n key "slogan") should take the user to home page of the app, but right now it just adds #home to the URL and does not redirect to the root page.
![Screen Shot 2021-08-16 at 9 08 37 PM](https://user-images.githubusercontent.com/1310940/129662641-e2ca4d25-c00a-43f4-9a40-1dbcd2cd6570.png)

**Comment by dpolozov** [comment]
fixed
